version: "2.2"

services:
  postgres-comexMachine:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=f_ship
      - POSTGRES_USER=f_ship
      - POSTGRES_DB=comexMachine
    volumes:
      - postgres-data:/var/lib/postgresql/comexMachine

volumes:
  postgres-data:
    driver: local
